// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Nxbpv9FLkKUSTZpLSWxnS5OtuSH5-bQ',
    appId: '1:889556655575:web:74e3a7c0e1561b97bf7f92',
    messagingSenderId: '889556655575',
    projectId: 'consentual-cc725',
    authDomain: 'consentual-cc725.firebaseapp.com',
    storageBucket: 'consentual-cc725.appspot.com',
    measurementId: 'G-D8GLB3SPSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4StCb0IXRM_ORlmZ_MW-QrgJoT3tfqpI',
    appId: '1:889556655575:android:3f65527351a1b48bbf7f92',
    messagingSenderId: '889556655575',
    projectId: 'consentual-cc725',
    storageBucket: 'consentual-cc725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW6GKJaePdPqmdMrnazLJjFa8k3KrSaLA',
    appId: '1:889556655575:ios:76c89fa9cd336ebfbf7f92',
    messagingSenderId: '889556655575',
    projectId: 'consentual-cc725',
    storageBucket: 'consentual-cc725.appspot.com',
    iosBundleId: 'com.example.consentual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW6GKJaePdPqmdMrnazLJjFa8k3KrSaLA',
    appId: '1:889556655575:ios:76c89fa9cd336ebfbf7f92',
    messagingSenderId: '889556655575',
    projectId: 'consentual-cc725',
    storageBucket: 'consentual-cc725.appspot.com',
    iosBundleId: 'com.example.consentual',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Nxbpv9FLkKUSTZpLSWxnS5OtuSH5-bQ',
    appId: '1:889556655575:web:904063716de0f22cbf7f92',
    messagingSenderId: '889556655575',
    projectId: 'consentual-cc725',
    authDomain: 'consentual-cc725.firebaseapp.com',
    storageBucket: 'consentual-cc725.appspot.com',
    measurementId: 'G-YECZ8MJRZY',
  );

}